version: "2"
services:
  jdownloader-2:
    image: jlesage/jdownloader-2
    ports:
      - 5800:5800
    volumes:
      - ./containers/jdownloader/Config/JDownloader-2:/config:rw
      - ./containers/jdownloader/YouTube:/output:rw
