---
version: "2.1"
services:
  pyload:
    image: ghcr.io/linuxserver/pyload
    container_name: pyload
    environment:
      - PUID=0
      - PGID=0
      - TZ=singapore
    volumes:
      - ./containers/pyload/config:/config
      - ./containers/pyload/downloads:/downloads
    ports:
      - 8000:8000
      - 7227:7227 #optional
    restart: unless-stopped
